---
title: "Untitled"
author: "Darreion Bailey"
date: "2024-03-16"
output: html_document
---

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
library(tidyverse)
df <- read.csv("../diamonds4.csv")
df$cut <- factor(df$cut, levels = c("Astor Ideal", "Ideal", "Very Good", "Good"))
```

## Initializing distributions

```{r}
# Create a histogram for the carat variable
ggplot(df, aes(x = carat)) +
  geom_histogram(binwidth = 0.1, fill = "blue", color = "black") +
  theme_minimal() +
  labs(title = "Distribution of Diamond Carat", caption="Figure 1: This chart shows the distribution of Carat. As illustrated, it shows a right skew favoring lower Carat weight. This is reflective of how people buy.", x = "Carat", y = "Frequency")
```

```{r}
# Create a bar chart for the clarity variable
ggplot(df, aes(x = clarity)) +
  geom_bar(fill = "orange", color = "black") +
  theme_minimal() +
  labs(title = "Frequency of Diamond Clarity Grades", caption="Figure 2: This chart shows the distribution of Clarity grades, and it is a left skewed bar chart.", x = "Clarity", y = "Frequency")

```

```{r}
# Create a bar chart for the color variable
ggplot(df, aes(x = color)) +
  geom_bar(fill = "green", color = "black") +
  theme_minimal() +
  labs(title = "Frequency of Diamond Color Grades", caption="Figure 3: This chart shows the distribution of Color grades.", x = "Color", y = "Frequency")

```

```{r}
# Create a bar chart for the cut variable
ggplot(df, aes(x = cut)) +
  geom_bar(fill = "purple", color = "black") +
  theme_minimal() +
  labs(title = "Frequency of Diamond Cut Qualities", caption="Figure 4: This chart shows the distribution of Cut qualities. Most of the diamonds sold/listed for sale belong to the Ideal category.", x = "Cut", y = "Frequency")

```

## Each variable vs. price

```{r}
# Scatter plot for Carat vs. Price
ggplot(df, aes(x = carat, y = price)) +
  geom_point(aes(color = cut), alpha = 0.5) + # Color points by cut to add more context
  theme_minimal() +
  labs(title = "Carat vs. Price", caption="Figure 5: This chart shows the distribution of Carat vs. Price, with cut added to add more context.", x = "Carat", y = "Price")

```

```{r}
# Box plot for Clarity vs. Price
ggplot(df, aes(x = clarity, y = price)) +
  geom_violin(aes(fill = clarity), show.legend = FALSE) +
  theme_minimal() +
  labs(title = "Clarity vs. Price", x = "Clarity", y = "Price",caption="Figure 6: This chart shows the distribution of Clarity vs. Price. Diamonds with FL and VS2 have the maximum price range ")

```

```{r}
# Box plot for Color vs. Price
ggplot(df, aes(x = color, y = price)) +
  geom_violin(aes(fill = color), show.legend = FALSE) +
  theme_minimal() +
  labs(title = "Color vs. Price", x = "Color", y = "Price",caption="Figure 7: This chart shows the distribution of Color vs. Price. Note that D being most superior carries the highest price")

```

```{r}
# Box plot for Cut vs. Price
ggplot(df, aes(x = cut, y = price)) +
  geom_violin(aes(fill = cut), show.legend = FALSE) +
  theme_minimal() +
  labs(title = "Cut vs. Price", x = "Cut", y = "Price",caption="Figure 8: This chart shows the distribution of Cut vs. Price")

```

```{r}
# Carat vs. Price by Clarity
ggplot(df, aes(x = carat, y = price)) +
  geom_point(aes(color = clarity), alpha = 0.5) +
  facet_wrap(~clarity) +
  theme_minimal() +
  labs(title = "Carat vs. Price by Clarity", x = "Carat", y = "Price",caption="Figure 9: This chart shows the distribution of Carat vs. Price broken down by clarity")
```

```{r}
# Carat vs. Price by Color
ggplot(df, aes(x = carat, y = price)) +
  geom_point(aes(color = color), alpha = 0.5) +
  facet_wrap(~color) +
  theme_minimal() +
  labs(title = "Carat vs. Price by Color", x = "Carat", y = "Price",caption="Figure 10: This chart shows the distribution of Carat vs. Price,broken down by color.")
```

```{r}
# Faceted Scatter Plot for Carat vs. Price by Cut
ggplot(df, aes(x = carat, y = price)) +
  geom_point(aes(color = cut), alpha = 0.5) +
  facet_wrap(~cut) +
  theme_minimal() +
  labs(title = "Carat vs. Price by Cut", x = "Carat", y = "Price",caption="Figure 11: This chart shows the distribution of Carat vs. Price,broken down by Cut ")
```

## Carat vs. All other variables

```{r}
ggplot(df, aes(x = clarity, y = carat)) +
  geom_violin(aes(fill = clarity)) +
  theme_minimal() +
  labs(title = "Carat vs. Clarity", x = "Clarity", y = "Carat",caption="Figure 12: This chart shows the distribution of Carat vs. Clarity")
```

```{r}
ggplot(df, aes(x = color, y = carat)) +
  geom_violin(aes(fill = color)) +
  theme_minimal() +
  labs(title = "Carat vs. Color", x = "Color", y = "Carat",caption="Figure 13: This chart shows the distribution of Carat vs. Color")
```

```{r}
ggplot(df, aes(x = cut, y = carat)) +
  geom_violin(aes(fill = cut), show.legend = FALSE) +
  theme_minimal() +
  labs(title = "Carat vs. Cut", x = "Cut", y = "Carat",caption="Figure 14: This chart shows the distribution of Carat vs Cut")
```

## Categorical comparisons

```{r}
ggplot(df, aes(x = clarity, fill = color)) +
  geom_bar(position = "fill") +
  theme_minimal() +
  labs(title = "Clarity vs. Color", x = "Clarity", y = "Proportion",caption="Figure 15: This chart shows the distribution of clarity vs Color")
```

```{r}
ggplot(df, aes(x = clarity, fill = cut)) +
  geom_bar(position = "dodge") +
  theme_minimal() +
  labs(title = "Clarity vs. Cut", x = "Clarity", y = "Count",caption="Figure 17: This chart shows the number of diamonds broken down by clarity and by cut ") 
```

```{r}
ggplot(df, aes(x = color, fill = cut)) +
  geom_bar(position = "stack") +
  theme_minimal() +
  labs(title = "Cut vs. Color", x = "Color", y = "Count",caption="Figure 18: This chart shows the distribution of dimaonds broken down by Color and Cut.")
```
